---
- name: create default configuration
  ini_file:
    path: /etc/samba/smb.conf
    section: global
    option: "{{ samba_default_option.name }}"
    value: "{{ samba_default_option.value }}"
    create: yes
    mode: 0644
  become: true
  notify: restart samba

