---
- block:
  - name: install samba
    package: name=samba state=present

  - name: start samba server
    service: name={{ _samba.samba_daemon[xfacts.distro.osfamily] }} state=started enabled=yes

  - name: start netbios server
    service: name={{ _samba.netbios_daemon[xfacts.distro.osfamily] }} state=started enabled=yes
  become: true

- include_tasks: create-default-config.yml
  vars:
    samba_default_option: "{{ item }}"
  with_items: "{{ samba_default_options }}"
