---
- name: get installed version
  command: minikube version warn=no
  changed_when: false
  failed_when: false
  check_mode: false
  register: _minikube_installed_release_result

- block:
  - name: get installed version
    set_fact:
      _minikube_installed_release: "{{ _minikube_installed_release_result.stdout | regex_replace('^.*?(v\\d+\\.\\d+\\.\\d+).*$', '\\1') }}"

  - block:
    - name: uninstall minikube:{{ _minikube_installed_release }}
      file: path="{{ minikube_bin_path }}" state=absent
    when: _minikube_installed_release is version(minikube_release, "!=")
    become: true
  when: _minikube_installed_release_result.rc == 0
