---
- name: run nexus:{{ dockered_nexus_version }}
  docker_container:
    name: "{{ dockered_nexus_container_name }}"
    image: "sonatype/nexus3:{{ dockered_nexus_version }}"
    state: started
    restart_policy: "{{ dockered_nexus_restart_policy }}"
    network_mode: "{{ dockered_nexus_network_mode }}"
    ports: "{{ dockered_nexus_ports }}"
  become: true # work around for https://github.com/ansible/ansible/issues/20604
