---
- include_tasks: install-docker.debian.yml
  when: xfacts.distro.name == 'debian'

- include_tasks: install-docker.ubuntu.yml
  when: (xfacts.distro.osfamily == 'debian') and (xfacts.distro.name != 'debian')

- name: start docker
  service: name=docker state=started enabled=yes
  become: true
