FROM alpine:3.8
LABEL maintainer="Varlog <varlog.err@gmail.com>"

# base layer, install tini and bash
RUN apk --no-cache upgrade && apk --no-cache add tini bash coreutils

# common layer, create app user and app directory
ENV APP_USER=app
ENV APP_GROUP=app
ENV APP_DIR=/app
RUN  addgroup -g 1000 ${APP_GROUP} \
  && adduser -D -H -G ${APP_GROUP} -s /bin/false -u 1000 ${APP_USER}
VOLUME ["${APP_DIR}"]
WORKDIR ${APP_DIR}

# often layer, install supervisor
RUN apk --no-cache add supervisor

# app layer
ENV SAMBA_CONF_DIR=/etc/samba
ENV SAMBA_CONF=${SAMBA_CONF_DIR}/smb.conf
ENV SAMBA_CUSTOM_CONF_DIR=${SAMBA_CONF_DIR}/conf.d

# install samba, and supervisor
RUN apk --no-cache add samba

# create custom config directory
RUN mkdir ${SAMBA_CUSTOM_CONF_DIR}

# copy assets
COPY docker-entrypoint-alpine.sh /usr/local/bin/docker-entrypoint.sh
COPY smb.conf /etc/samba
COPY supervisord.conf /etc/

# change binaries permission
RUN chmod 0700 /usr/local/bin/docker-entrypoint.sh

# exposes samba default ports (137, 138 for nmbd and 139, 445 for smbd)
EXPOSE 137/udp 138/udp 139 445

ENTRYPOINT ["tini", "--"]
CMD docker-entrypoint.sh
