---
- include_tasks: uninstall-desk.yml

- name: install desk:{{ desk_version }}
  get_url:
    url: https://raw.githubusercontent.com/jamesob/desk/v{{ desk_version }}/desk
    dest: "{{ desk_bin_path }}"
    mode: 0755
  become: true
