---
- name: get installed version
  command: desk --version warn=no
  changed_when: false
  failed_when: false
  check_mode: false
  register: _desk_installed_version_tmp

- block:
  - set_fact:
      _desk_installed_version: "{{ _desk_installed_version_tmp.stdout | regex_replace('^[^\\d]+(\\d+\\.\\d+\\.\\d+).*$', '\\1') }}"

  - name: uninstall desk:{{ _desk_installed_version }}
    file: path="{{ desk_bin_path }}" state=absent
    when: _desk_installed_version is version(desk_version, "!=")
    become: true

  when: _desk_installed_version_tmp.rc == 0
