---
- fail: msg="helper_launchpad_installer.pkg is required"
  when: helper_launchpad_installer.pkg is undefined

- fail: msg="helper_launchpad_installer.ppa is required for {{ helper_launchpad_installer.pkg }}"
  when: helper_launchpad_installer.ppa is undefined

- fail: msg="helper_launchpad_installer.fingerprint is required for {{ helper_launchpad_installer.pkg }}"
  when: helper_launchpad_installer.fingerprint is undefined

- include_role: name=uni.helper-launchpad-ppa
  vars:
    helper_launchpad_ppa: "{{ helper_launchpad_installer }}"

- name: install '{{ helper_launchpad_installer.pkg }}'
  apt: name="{{ helper_launchpad_installer.pkg }}" update_cache=yes state=latest
  become: true
