---
- block:
  - name: add erlang solutions repository
    apt: deb=https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb state=present
    when: xfacts.distro.osfamily == 'debian'

  - name: add erlang solutions repository
    yum: name=https://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm state=present
    when: xfacts.distro.osfamily == 'redhat'
  become: true
