---
- include_tasks: add-repo.debian.yml
  when: xfacts.distro.osfamily == 'debian'

- include_tasks: add-repo.redhat.yml
  when: xfacts.distro.osfamily == 'redhat'

- block:
  - name: install docker
    package: name=docker-ce state=present

  - name: start docker
    service: name=docker state=started enabled=yes

  - name: change defaults
    lineinfile:
      path: /etc/default/docker
      line: "{{ item }}"
      create: yes
    with_items: "{{ docker_defaults }}"
    notify: restart docker

  - name: create '{{ docker_group }}' group
    group: name={{ docker_group }} state=present

  - name: add users to '{{ docker_group }}' group
    user: name="{{ item }}" groups={{ docker_group }} append=yes
    loop: "{{ docker_group_users }}"
  become: true
