---
- include_tasks: install-docker.debian.yml
  when: xfacts.distro.name == 'debian'

- include_tasks: install-docker.ubuntu.yml
  when: (xfacts.distro.osfamily == 'debian') and (xfacts.distro.name != 'debian')

- include_tasks: install-docker.redhat.yml
  when: xfacts.distro.osfamily == 'redhat'

- block:
  - name: start docker
    service: name=docker state=started enabled=yes

  - name: change defaults
    lineinfile:
      path: /etc/default/docker
      line: "{{ item }}"
      create: yes
    with_items: "{{ docker_defaults }}"
    notify: restart docker
  become: true
