---
- name: override defaults
  set_fact:
    _desk:
      version: "{{ desk.version | default(_desk_defaults.version) }}"
      bin_path: "{{ _desk.bin_path }}"

- include_tasks: uninstall-desk.yml

- name: install desk:{{ _desk.version }}
  get_url:
    url: https://raw.githubusercontent.com/jamesob/desk/v{{ _desk.version }}/desk
    dest: "{{ _desk.bin_path }}"
    mode: 0755
  become: true
