---
- set_fact:
    golang_pkg: "golang-{{ golang_version }}-go"

- set_fact:
    golang_pkg: "golang-{{ golang_version }}"
  when: golang_full

- include_tasks: "main.{{ xfacts.distro.osfamily }}.yml"
