---
- name: checkout asdf
  git: repo={{ asdf_repo }} dest={{ asdf_dir }} version={{ asdf_version }}

- name: add asdf to bashrc
  lineinfile:
    dest: "{{ xfacts.user.homedir }}/{{ item }}"
    create: yes
    mode: 0644
    line: ". {{ asdf_dir }}/asdf.sh"
    insertafter: EOF
  loop:
  - .bashrc
  - .profile

- name: add asdf completions to bashrc
  lineinfile:
    dest: "{{ xfacts.user.homedir }}/.bashrc"
    create: yes
    mode: 0644
    line: ". {{ asdf_dir }}/completions/asdf.bash"
    insertafter: EOF
