---
- name: install common asdf plugins dependencies
  apt: name="{{ packages }}" install_recommends=no state=present
  vars:
    packages:
      - autoconf
      - automake
      - build-essential
      - gcc
      - libncurses5-dev
      - libffi-dev
      - libreadline-dev
      - libssl-dev
      - libtool
      - libxslt-dev
      - libyaml-dev
      - unzip
      - unixodbc-dev
  become: true
