---
- name: checkout asdf
  git: repo={{ asdf_repo }} dest={{ asdf_dir }} version={{ asdf_version }}

- name: add asdf to bashrc
  copy:
    dest: "{{ bashrc_source_dir }}/asdf.sh"
    content: |
      . {{ asdf_dir }}/asdf.sh
      . {{ asdf_dir }}/completions/asdf.bash
      # fix issue https://github.com/asdf-vm/asdf-nodejs/issues/82
      NODEJS_CHECK_SIGNATURES=no

- name: add asdf to profile
  lineinfile:
    dest: "{{ xfacts.user.homedir }}/.profile"
    create: yes
    mode: 0644
    line: ". {{ asdf_dir }}/asdf.sh"
    insertafter: EOF
