---
- name: set internal mapping
  set_fact:
    _helper_facts:
      mapping: "{{ _helper_facts.mapping }}"
      map: "{{ _helper_facts.mapping.debian[ansible_lsb.codename] }}"

- name: >
      set distro to '{{ _helper_facts.map.distro }}'
      and distro codename to '{{ ansible_lsb.codename }}'
  set_fact:
    helper_facts_distro: {
      name: "{{ _helper_facts.map.distro }}",
      codename: "{{ ansible_lsb.codename }}"
    }

- name: >
      map {{ helper_facts_distro.name }} '{{ helper_facts_distro.codename }}' codename
      to ubuntu '{{ _helper_facts.map.ubuntu_codename }}'
  set_fact:
    helper_facts_distro: {
      name: "{{ helper_facts_distro.name }}",
      codename: "{{ helper_facts_distro.codename }}",
      ubuntu_codename: "{{ _helper_facts.map.ubuntu_codename }}"
    }

- name: >
      set '{{ helper_facts_distro.name }}:{{ helper_facts_distro.codename }}'
      distro osfamily to '{{ _helper_facts.map.osfamily }}'
  set_fact:
    helper_facts_distro: {
      name: "{{ helper_facts_distro.name }}",
      codename: "{{ helper_facts_distro.codename }}",
      ubuntu_codename: "{{ helper_facts_distro.ubuntu_codename }}",
      osfamily: "{{ _helper_facts.map.osfamily }}"
    }
