---
- include_role: name=uni.helper-launchpad-installer
  vars:
    helper_launchpad_installer:
      pkg: "{{ _golang.pkg }}"
      ppa: gophers/archive
      fingerprint: C73998DC9DFEA6DCF1241057308C15A29AD198E9
