---
- include_vars: "{{ xfacts.distro.osfamily }}.yml"
- include_tasks: "add-repo-{{ xfacts.distro.osfamily }}.yml"

- block:
  - name: install mariadb client
    package: name="{{ mariadb_package_client_name }}" state=present
    when: mariadb_install_client | bool

  - block:
    - name: install mariadb server
      package: name="{{ mariadb_package_server_name }}" state=present

    - name: start mariadb
      service: name=mysql state=started enabled=yes
    when: mariadb_install_server | bool
  become: true
