---
- name: set internal mapping
  set_fact:
    _helper_facts:
      distro:
        map: "{{ _helper_facts.distro.map.debian[ansible_lsb.codename] }}"

- name: setup distro helper facts
  set_fact:
    helper_facts: "{{ helper_facts | combine({'distro': {
      'name': _helper_facts.distro.map.name,
      'codename': ansible_lsb.codename,
      'ubuntu_codename': _helper_facts.distro.map.ubuntu_codename,
      'osfamily': _helper_facts.distro.map.osfamily
    }})}}"
