---
- include_vars: "{{ xfacts.distro.osfamily }}.yml"

- block:
  - name: install apache
    package: name={{ apache_package_name }} state=present

  - name: start apache
    service: name={{ apache_service_name }} state=started enabled=yes
  become: yes
