---
- include_tasks: uninstall-docker-compose.yml

- block:
  - name: install docker-compose:{{ docker_compose_version }}
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
      dest: "{{ docker_compose_bin_path }}"
      mode: 0755

  - name: install docker-compose:{{ docker_compose_version }} bash completion
    get_url:
      url: https://raw.githubusercontent.com/docker/compose/{{ docker_compose_version }}/contrib/completion/bash/docker-compose
      dest: "{{ docker_compose_bash_completion_path }}"
      mode: 0644
  become: true
