---
- name: get installed version
  command: docker-compose --version warn=no
  changed_when: false
  failed_when: false
  check_mode: false
  register: _docker_compose_installed_version_result

- block:
  - name: get installed version
    set_fact:
      _docker_compose_installed_version: "{{ _docker_compose_installed_version_result.stdout | regex_replace('^.*?(\\d+\\.\\d+\\.\\d+)[^\\d].*$', '\\1') }}"

  - block:
    - name: uninstall docker-compose:{{ _docker_compose_installed_version }}
      file: path="{{ docker_compose_bin_path }}" state=absent

    - name: uninstall docker-compose:{{ _docker_compose_installed_version }} bash completion
      file: path="{{ docker_compose_bash_completion_path }}" state=absent
    when: _docker_compose_installed_version is version(docker_compose_version, "!=")
    become: true
  when: _docker_compose_installed_version_result.rc == 0
