---
- set_fact:
    _php_version: "{{ php_version | regex_replace('(\\d+)\\.(\\d+)$', '\\1\\2') }}"

- name: install php-{{ _php_extension }}
  yum: name="php-{{ _php_extension }}" enablerepo=remi-php{{ _php_version }} state=present
  become: true
