---
- set_fact:
    _php_version: "{{ php_version | regex_replace('(\\d+)\\.(\\d+)$', '\\1\\2') }}"
  
- name: install php:{{ php_version }}
  yum: name=php enablerepo=epel,remi-php{{ _php_version }} state=present
  become: true
