---
- include_tasks: uninstall-kubectl.yml

- block:
  - name: install kubectl:{{ kubectl_version }}
    get_url:
      url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
      dest: "{{ kubectl_bin_path }}"
      mode: 0755
    register: _kubectl_installed_result

  - name: create autocomplete
    shell: "{{ kubectl_bin_path }} completion bash > {{ kubectl_autocomplete_path }}"
    when: _kubectl_installed_result.changed
  become: true
