---
- block:
  - name: install kubectx
    get_url:
      url: https://raw.githubusercontent.com/ahmetb/kubectx/v{{ kubectx_version }}/kubectx
      dest: "{{ kubectx_bin_path }}"
      mode: 0755
  
  - name: install kubectx completion
    get_url:
      url: https://raw.githubusercontent.com/ahmetb/kubectx/v{{ kubectx_version }}/completion/kubectx.bash
      dest: "{{ kubectx_autocomplete_path }}"
      mode: 0644

  - name: install kubens
    get_url:
      url: https://raw.githubusercontent.com/ahmetb/kubectx/v{{ kubectx_version }}/kubens
      dest: "{{ kubens_bin_path }}"
      mode: 0755
  
  - name: install kubens completion
    get_url:
      url: https://raw.githubusercontent.com/ahmetb/kubectx/v{{ kubectx_version }}/completion/kubens.bash
      dest: "{{ kubens_autocomplete_path }}"
      mode: 0644
  become: true
