---
- set_fact:
    _samba_share_rm_paths: []
    _samba_share_added_paths: []

- name: gather share configurations
  find:
    paths: "{{ samba_share_confd }}"
    patterns: '*.conf'
    file_type: file
    recurse: no
  register: _samba_share_all

- name: make created shares configuration list
  set_fact:
    _samba_share_added_paths: "{{ _samba_share_added_paths }} + ['{{ samba_share_confd }}/{{ item }}.conf']"
  with_items: "{{ samba_share_confs.keys() }}"

- name: gather old configuration
  set_fact:
    _samba_share_rm_paths: "{{ _samba_share_rm_paths }} + ['{{ item.path }}']"
  when: item.path not in _samba_share_added_paths
  with_items: "{{ _samba_share_all.files }}"

- name: clean up samba main config
  lineinfile:
    dest: "{{ samba_conf_path }}"
    line: "include = {{ item }}"
    state: absent
  with_items: "{{ _samba_share_rm_paths }}"
  notify: restart samba
  become: true

- name: remove config files
  file: path="{{ item }}" state=absent
  with_items: "{{ _samba_share_rm_paths }}"
  notify: restart samba
  become: true
