---
- include_tasks: create-dir.yml
  vars:
    samba_share_dir: "{{ item }}"
  with_items: "{{ samba_share_dirs }}"

- name: create ansible managed config directory
  file: path="{{ samba_share_confd }}" state=directory
  become: true

- include_tasks: create-share.yml
  vars:
    samba_share_conf_file: "{{ samba_share_confd }}/{{ item.key }}.conf"
    samba_share_conf_content: "{{ item.value }}"
  with_dict: "{{ samba_share_confs }}"

- include_tasks: clean-up-shares.yml
