---
- block:
  - name: restart samba
    service: name={{ _samba.samba_daemon[xfacts.distro.osfamily] }} state=restarted

  - name: restart netbios
    service: name={{ _samba.netbios_daemon[xfacts.distro.osfamily] }} state=restarted
  become: true
