---
- name: setup distro helper facts
  set_fact:
    xfacts: "{{ xfacts | combine({'distro': {
      'name': ansible_distribution | lower,
      'osfamily': ansible_os_family | lower,
      'major_version': ansible_distribution_major_version,
      'minor_version': ansible_distribution_version | regex_replace('^\\d+\\.(\\d+)\\.\\d+$', '\\1'),
      'full_version': ansible_distribution_version,
    }})}}"
