---
- name: set internal mapping
  set_fact:
    _xfacts_distromap: "{{ _xfacts.distro.map.debian[ansible_lsb.codename] }}"

- name: setup distro helper facts
  set_fact:
    xfacts: "{{ xfacts | combine({'distro': {
      'name': _xfacts_distromap.name,
      'osfamily': _xfacts_distromap.osfamily,
      'codename': ansible_lsb.codename,
      'ubuntu_codename': _xfacts_distromap.ubuntu_codename,
    }})}}"
