---
- name: prepare build time
  set_fact:
    _xfacts_build_time: "{{ansible_date_time.date}}_{{ansible_date_time.hour}}-{{ansible_date_time.minute}}-{{ansible_date_time.second}}"

- name: setup system facts
  set_fact:
    xfacts: "{{ xfacts | combine({'system': {
      'ansible_managed_pascal_case': 'AnsibleManaged',
      'ansible_managed_text': 'ansible managed',
      'ansible_managed_prefix': 'ansible-managed',
      'ansible_managed_hidden_prefix': '.ansible-managed',
      'build_time': _xfacts_build_time,
      'build_timestamp': ansible_date_time.epoch,
    }})}}"
