---
- include_tasks: uninstall-yq.yml

- block:
  - name: install yq:{{ yq_version }}
    get_url:
      url: https://github.com/mikefarah/yq/releases/download/{{ yq_version }}/yq_linux_amd64
      dest: "{{ yq_bin_path }}"
      mode: 0755
  become: true
