---
- block:
  - name: add apt signing key
    apt_key:
      url: "https://download.sublimetext.com/sublimehq-pub.gpg"
      state: present

  - name: add ppa
    apt_repository:
      repo: 'deb https://download.sublimetext.com/ apt/stable/'
      filename: sublime-text
      state: present

  - name: install sublime text
    apt: name=sublime-text update_cache=yes state=latest
  become: true
