---
- include_role: name=helper-launchpad-ppa
  vars:
    helper_launchpad_ppa:
      ppa: deluge-team/ppa
      fingerprint: 8EED8FB4A8E6DA6DFDF0192BC5E6A5ED249AD24C
  when: xfacts.distro.osfamily == 'debian'

- name: install deluge
  apt: name=deluge
  become: true
