---
- include_tasks: create-dir.yml
  vars:
    samba_shares_dir: "{{ item }}"
  with_items: "{{ samba_shares_dirs }}"

- name: create ansible managed config directory
  file: path="{{ samba_shares_confd }}" state=directory
  become: true

- include_tasks: create-share.yml
  vars:
    samba_shares_conf_file: "{{ samba_shares_confd }}/{{ item.key }}.conf"
    samba_shares_conf_content: "{{ item.value }}"
  with_dict: "{{ samba_shares_confs }}"

- include_tasks: clean-up-shares.yml
