---
- block:
  - name: install package
    unarchive: src={{ fzf_tgz_url }} dest={{ fzf_bin_prefix }} mode=0755 remote_src=yes

  - name: checkout fzf
    git: repo={{ fzf_repo }} dest={{ fzf_src_dir }} version={{ fzf_version }}
  become: true

- name: create fzf bash
  template: src=fzf.bash dest="{{ bashrc_source_dir }}/fzf.sh" mode=0644

- name: source fzf configuration file
  template: dest="{{ bashrc_source_dir }}/fzfrc.sh" src="{{ fzf_fzfrc }}"
