---
- block:
  - name: add apt-key
    apt_key:
      url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
      state: present

  - name: add ppa
    apt_repository:
      repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
      filename: google-chrome
      state: present

  - name: install google chrome
    apt: name=google-chrome-stable state=latest
  become: true
