FROM debian:9.8-slim
LABEL maintainer="Varlog <varlog.err@gmail.com>"

ARG APP_USER_DEFAULT=app
ARG APP_USER_ID_DEFAULT=1000
ARG APP_GROUP_DEFAULT=app
ARG APP_GROUP_ID_DEFAULT=1000

ENV TINI_VERSION=v0.18.0 \
    APP_USER=${APP_USER_DEFAULT} \
    APP_USER_ID=${APP_USER_ID_DEFAULT} \
    APP_GROUP=${APP_GROUP_DEFAULT} \
    APP_GROUP_ID=${APP_GROUP_ID_DEFAULT} \
    APP_DIR=/app \
    SAMBA_CONF_DIR=/etc/samba

ENV SAMBA_CONF=${SAMBA_CONF_DIR}/smb.conf \
    SAMBA_CUSTOM_CONF_DIR=${SAMBA_CONF_DIR}/conf.d

RUN : \
    # install supervisor
    && apt-get update && apt-get install -y supervisor \
    # install samba
    && apt-get install -y samba \
    # create app user and group
    && addgroup -q --gid ${APP_GROUP_ID} ${APP_GROUP} \
    && adduser -q --disabled-login \
      --ingroup ${APP_GROUP} \
      --shell /bin/false \
      --no-create-home --uid ${APP_USER_ID} ${APP_USER} \
    # create custom config directory
    && mkdir ${SAMBA_CUSTOM_CONF_DIR} \
    # clean up
    && apt-get -y clean \
    && apt-get -y autoclean \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

VOLUME ["${APP_DIR}"]
WORKDIR ${APP_DIR}

# copy assets
COPY docker-entrypoint-debian.sh /usr/local/bin/docker-entrypoint.sh
COPY smb.conf /etc/samba
COPY supervisord.conf /etc/
# install tini
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/local/bin

# change binaries permission
RUN : \
    && chmod 0700 /usr/local/bin/docker-entrypoint.sh \
    && chmod 0700 /usr/local/bin/tini

# exposes samba default ports (137, 138 for nmbd and 139, 445 for smbd)
EXPOSE 137/udp 138/udp 139 445

ENTRYPOINT ["tini", "--"]
CMD docker-entrypoint.sh
