FROM alpine:3.9
LABEL maintainer="Varlog <varlog.err@gmail.com>"

ARG APP_USER_DEFAULT=app
ARG APP_USER_ID_DEFAULT=1000
ARG APP_GROUP_DEFAULT=app
ARG APP_GROUP_ID_DEFAULT=1000

ENV APP_USER=${APP_USER_DEFAULT} \
    APP_USER_ID=${APP_USER_ID_DEFAULT} \
    APP_GROUP=${APP_GROUP_DEFAULT} \
    APP_GROUP_ID=${APP_GROUP_ID_DEFAULT} \
    APP_DIR=/app \
    SAMBA_CONF_DIR=/etc/samba

ENV SAMBA_CONF=${SAMBA_CONF_DIR}/smb.conf \
    SAMBA_CUSTOM_CONF_DIR=${SAMBA_CONF_DIR}/conf.d

RUN : \
    # install tini and bash
    && apk --no-cache --update add tini bash coreutils \
    # install supervisor
    supervisor \
    #  install samba
    samba \
    # create app user and group
    && addgroup -g ${APP_GROUP_ID} ${APP_GROUP} \
    && adduser -D -H -G ${APP_GROUP} -s /bin/false -u ${APP_USER_ID} ${APP_USER} \
    # create custom config directory
    && mkdir ${SAMBA_CUSTOM_CONF_DIR}

VOLUME ["${APP_DIR}"]
WORKDIR ${APP_DIR}

# copy assets
COPY docker-entrypoint-alpine.sh /usr/local/bin/docker-entrypoint.sh
COPY smb.conf /etc/samba
COPY supervisord.conf /etc/

# change binaries permission
RUN chmod 0700 /usr/local/bin/docker-entrypoint.sh

# expose samba default ports (137, 138 for nmbd and 139, 445 for smbd)
EXPOSE 137/udp 138/udp 139 445

ENTRYPOINT ["tini", "--"]
CMD docker-entrypoint.sh
