---
- name: override defaults
  set_fact:
    _dockered_nexus3:
      version: "{{ dockered_nexus3.version | default(_dockered_nexus3_defaults.version) }}"
      network_mode: "{{ dockered_nexus3.network_mode | default(_dockered_nexus3_defaults.network_mode) }}"

- name: run nexus3:{{ _dockered_nexus3.version }}
  docker_container:
    name: nexus3
    image: "sonatype/nexus3:{{ _dockered_nexus3.version }}"
    state: started
    restart_policy: unless-stopped
    network_mode: "{{ _dockered_nexus3.network_mode }}"
  # 'become: true' as work around for https://github.com/ansible/ansible/issues/20604
  become: true
