---
- name: create hosts file
  file: path="{{ hosts_file_file_path }}" state=file mode=0644
  become: true

- include_tasks: add-host.yml
  vars:
    _hosts_file_domain: "{{ item.key }}"
    _hosts_file_ip: "{{ item.value }}"
  with_dict: "{{ hosts_file_host_to_ip_map }}"
