---
- include_role: name=helper-launchpad-ppa
  vars:
    helper_launchpad_ppa:
      ppa: videolan/stable-daily
      fingerprint: 3361E59FF5029E6B90A9A80D09589874801DF724
      ubuntu_codename: xenial
  when: xfacts.distro.osfamily == 'debian'

- name: install vlc
  apt: name=vlc
  become: true
