---
- block:
  - name: add apt signing key
    apt_key:
      url: "https://repo.skype.com/data/SKYPE-GPG-KEY"
      state: present

  - name: add ppa
    apt_repository:
      repo: 'deb [arch=amd64] https://repo.skype.com/deb stable main'
      filename: skype-stable
      state: present

  - name: install skype
    apt: name=skypeforlinux state=latest
  when: xfacts.distro.osfamily == 'debian'
  become: true
