---
- block:
  # This command will fail when the root password was set previously
  - name: check if root password is set
    shell: mysqladmin -u root status
    changed_when: false
    failed_when: false
    register: _mariadb_root_password_check

  - name: set root password for the first time (root@localhost)
    mysql_user:
      name: root
      password: "{{ mariadb_root_password }}"
      host: localhost
      state: present
      login_user: root
    when: _mariadb_root_password_check.rc == 0
  when: mariadb_root_password is defined
